// <auto-generated />
namespace GroceryMinder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameGroceryListCompletionTokenstoCompletionTokens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameGroceryListCompletionTokenstoCompletionTokens));
        
        string IMigrationMetadata.Id
        {
            get { return "201602200706207_Rename GroceryListCompletionTokens to CompletionTokens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
