// <auto-generated />
namespace GroceryMinder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPriorityFieldtoGroceryCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPriorityFieldtoGroceryCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201602180448448_Add Priority Field to GroceryCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
